TRANSACTION_AMOUNT_FILTER = 20
TRANSACTION_DATE_FILTER = 2010
TRANSACTION_INPUT_DATE_FORMAT = "%Y-%m-%d %H:%M:%S %Z"
TRANSACTION_OUTPUT_DATE_FORMAT = "%Y-%m-%d"
TRANSACTION_OUTPUT_HEADER = "date, total_amount"
TRANSACTION_OUTPUT_GZIP_FORMAT = ".jsonl.gz"
